export const API_ERROR_CODES = {
    BAD_REQUEST: "BAD_REQUEST",
    PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ApiErrorCode =
    (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
